/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\Lenovo\ThreerDemo\src\scene\Models\free_iphone_13_pro_2021.glb -t 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone-13-pro-2021-a35156d91cf44e70a2fdfeade54ae0b2
Title: (FREE) iPhone 13 Pro 2021
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Back: THREE.MeshStandardMaterial
    GOLD: THREE.MeshStandardMaterial
    BARRES: THREE.MeshStandardMaterial
    Labber: THREE.MeshStandardMaterial
    GLASS: THREE.MeshStandardMaterial
    Lenscover: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Display: THREE.MeshStandardMaterial
    ['Lens.2']: THREE.MeshStandardMaterial
    material_11: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/free_iphone_13_pro_2021.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.545}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.104, 1.448, -0.258]} scale={0.043}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Black} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Back} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.GOLD} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.BARRES} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.Labber} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.GLASS} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Lenscover} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Display} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Lens.2']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.material_11} />
          </group>
          <group position={[-0.136, 1.448, 1.545]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.043}>
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.Black} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Back} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.GOLD} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.BARRES} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Labber} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.GLASS} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Lenscover} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.Display} />
            <mesh geometry={nodes.Object_27.geometry} material={materials['Lens.2']} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.material_11} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/free_iphone_13_pro_2021.glb')
